name = "aj-personal-agent"
compatibility_date = "2023-10-30"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.staging]
vars = { ENVIRONMENT = "staging" }

# KV Namespace for caching (optional)
[[kv_namespaces]]
binding = "AJ_AGENT_CACHE"
id = "your-kv-namespace-id" # Replace with your KV namespace ID

# Durable Objects for sessions (optional)
[[durable_objects]]
binding = "SESSIONS"
class_name = "SessionManager"

# Pages configuration
[pages]
build_output_dir = "public"

# Worker routes
[[routes]]
pattern = "api/chat"
zone_name = "your-domain.com" # Replace with your domain
script = "api/chat"

[[routes]]
pattern = "api/providers"
zone_name = "your-domain.com"
script = "api/providers"

[[routes]]
pattern = "api/health"
zone_name = "your-domain.com"
script = "api/health"
